rft_sensor_serial:
  ros__parameters:
    DEV_NAME: "/dev/ttyUSB"
    PORT: 0
    BAUD: 921600
    FORCE_DIVIDER: 50.00
    TORQUE_DIVIDER: 2000.00
    FREQUENCY: 500
    SET_CUTOFF_FILTER: True
    FILTER_FREQUENCY: 100
    BIAS_FX: 6.93
    BIAS_FY: 2.53
    BIAS_FZ: 28.3
    BIAS_TX: 0.49
    BIAS_TY: 0.1
    BIAS_TZ: -0.113