controller_manager:
  ros__parameters:
    update_rate: 200  # Hz

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

velocity_controller:
  ros__parameters:
    joints:
      - joint0
      - joint11
      - joint21
      - jointem
      - jointei

    state_interfaces:
      - velocity

joint_trajectory_controller:
  ros__parameters:
    joints:
      - joint0
      - joint11
      - joint21
      - jointem
      - jointei

    command_interfaces:
      - position

    state_interfaces:
      - position

    state_publish_rate: 100.0
    action_monitor_rate: 50.0
    open_loop_control: false
